name: Check Due Reminders

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'

jobs:
  send-reminders:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Reminder Notifications
        env:
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
        run: |
          curl -X GET https://robobison-2024.vercel.app//reminders/send \
          -H "Authorization: Bearer $API_SECRET_KEY"
